### DISCUSSION TITLE
Can I customize the TUI?

### DISCUSSION THREAD

**Discussion by ankitpokhrel** [ankitpokhrel/jira-cli#522] [FAQs]
It is not possible to fully customize the TUI at this moment. However, there is an option available to change the look of the selected row. You can add the following section in your config to do that.

```yaml
tui:
  selection:
    foreground: olive
    background: grey
    bold: true
```
List of valid colors can be found [here](https://github.com/gdamore/tcell/blob/e15e96cbcae1cd93791c337294f2cb37838b8788/color.go#L846-L991). The config needs to be added manually for now and will be overwritten if you run `jira init` again.
