### DISCUSSION TITLE
Filter by kanban board

### DISCUSSION THREAD

**Discussion by jamesgecko** [ankitpokhrel/jira-cli#679] [Q&A]
I feel like I must be missing something obvious. I ran the `jira config init` command, and verified that my board attributes appear at the top of `~/.config/.jira/.config.yml`:
```yaml
board:
    id: 95
    name: Attribution
    type: kanban
```

But when I run `jira issue list --paginate 20 --status="Peer Review"`, the output shows tickets from other boards. This seems to happen with any query. How do I scope this to only show tickets from the board in my config?
