### DISCUSSION TITLE
How to configure jira-cli for on-premise Jira installation with language other than English

### DISCUSSION THREAD

**Discussion by chirogocki** [ankitpokhrel/jira-cli#779] [Q&A]
Hi,

In documentation I see : 

> In that case, you will have to fill in epic.name, epic.link and issue.types.*.handle fields manually in the generated config to get the expected behavior.

but I don't know what to do with my config. I have :

```
issue
    types:
        - id: "10001"
          name: Tâche
          handle: ""
          subtask: false
        - id: "5"
          name: Sous-tâche
          handle: ""
          subtask: true
        - id: "20"
          name: Récit
          handle: ""
          subtask: false
        - id: "10003"
          name: Bogue
          handle: ""
          subtask: false
        - id: "19"
          name: Épopée
          handle: ""
          subtask: false
```
Here is the translation :
- Tâche = Task
- Sous-tâche = Sub-Task
- Récit = Story
- Bogue = Bug
- Épopée = Epic

Can you tell me what should I do with the field handle ?

Here is my server info :
```
SERVER INFO
-----------

Version:         7.6.3
Build Number:    76005
Deployment Type: Server
Default Locale: 
```

Thank you
