### DISCUSSION TITLE
Directory-specific config

### DISCUSSION THREAD

**Discussion by Virakal** [ankitpokhrel/jira-cli#846] [General]
I'm looking at moving over from the [go-jira CLI](https://github.com/go-jira/jira) but I'm struggling to figure out how to override configs based on the current directory. At the very basic level with go-jira I can commit a file

```yml
# this is .jira.d/config.yml

endpoint: https://redacted.atlassian.net/
project: ABC
```
to the repo and then anybody who pulls it just needs to set the `JIRA_API_TOKEN` env var and `jira list`, `jira create` etc. will use the correct project automatically. Surely there's some way to do the same on this project that I'm struggling to find the docs for?
