### ISSUE TITLE
Tracking issue for self-hosted support

### ISSUE THREAD

**Issue by cedws** [ankitpokhrel/jira-cli#132]
Ah, I was so excited to be able to escape the horrific Jira UI, but alas I see this project doesn't support self-hosted instances. 😢

Not sure what the API differences are but maybe I can lend a hand.

How about a tracking issue?

**Comment by ankitpokhrel** [comment]
Hi @cedws, thank you for opening the tracking issue. 

First thing we need to do is to figure out which of the current features already works in the local installation. I think some of the features should just work with little to no modifications. Once we have the list of possible issues we need to fix, we can visit them one by one.

To start with this first step, we need to make the `jira init` command work. However, this step can be bypassed by writing the config file manually (`$HOME/.jira/.config.yml` by default, we can provide a custom path with `XDG_CONFIG_HOME` env).

```yaml
board:
  id: <board id, eg: 1>
  name: Board # default board
  type: scrum
epic:
  field: customfield_10011 # custom field name for the epic
issue: # issue types, these info can be fetched from this endpoint https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/#api-rest-api-3-issue-createmeta-get
  types:
  - id: "10002"
    name: Task
    subtask: false
  - id: "10003"
    name: Sub-task
    subtask: true
  - id: "10001"
    name: Story
    subtask: false
  - id: "10004"
    name: Bug
    subtask: false
  - id: "10000"
    name: Epic
    subtask: false
login: example@company.com # login email
project: PRJ # project key
server: https://example.company.com # server host
```

It would be great if someone can help with this part.
