### ISSUE TITLE
'accountId' must be the only user identifying query parameter in GDPR strict mode

### ISSUE THREAD

**Issue by GZLiew** [ankitpokhrel/jira-cli#342]
**Describe the bug**

I was trying to assign a ticket to an user using the search box but was getting the following error

![image](https://user-images.githubusercontent.com/43195293/162712921-8b7b5c0c-4c24-4ed2-b99f-ebe2089f8266.png)
![image](https://user-images.githubusercontent.com/43195293/162712953-cd4b6115-767d-4753-a7e1-2ff5b002c998.png)

**Please provide following details**
1. JiraCLI Version: 
    0.3.0

2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    local use

3. What operating system are you using? Also mention version.
    macOS Big Sur 11.5.1

4. What terminal are you using? Also mention version.
    terminal

**Comment by ankitpokhrel** [comment]
@GZLiew How can I enable "GDPR strict mode" in Jira? Is it an option in the UI or hardcoded in config somewhere by Atlassian? I couldn't find proper details on this 😬

**Comment by dtsyosh** [comment]
https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/

@ankitpokhrel 

This is due to these changes.

 When I try to assign to other users I can, this error just occurs when I try to assign an issue to me.

**Comment by ankitpokhrel** [comment]
@dtsyosh I wonder why I can't reproduce this in my installation (both cloud and on-premise). Unless there is some config to enable the "GDPR strict mode", I should be easily able to reproduce this right?

**Comment by GZLiew** [comment]
@ankitpokhrel is there a verbose setting I can turn on so I can share you the logs while running the cli? heres the config im using.

```yaml
board:
  id: 24
  name: Developer board
  type: kanban
epic:
  name: ""
  link: ""
installation: Local
issue:
  types:
  - id: "10031"
    name: Component
    handle: Component
    subtask: false
  - id: "10030"
    name: Infrastructure
    handle: Infrastructure
    subtask: false
  - id: "10004"
    name: Bug
    handle: Bug
    subtask: false
  - id: "10033"
    name: Security Issue
    handle: Security Issue
    subtask: false
login: guozhangliew@gmail.com
project:
  key: SOLID
  type: classic
server: https://demo.atlassian.net
```
