### ISSUE TITLE
create issue with 400 error, msg: gh.epic.error.not.found

### ISSUE THREAD

**Issue by NagleZhang** [ankitpokhrel/jira-cli#344]
**Describe the bug**
```
~/code/open-source/jira-cli (main) » jira issue create                                     
? Issue type Task
? Parent issue key parent-151
? Summary test
? Description <Received>
? What's next? Submit

Error:
  - gh.epic.error.not.found

jira: Received unexpected response '400 '.
Please check the parameters you supplied and try again.
```

**Please provide following details**
1. JiraCLI Version:
    ```
   Version="main", GitCommit="da5082c56c8ca5d10d3e96210d7f6cf9978e2b4e", CommitDate="2022-03-01T19:31:59+00:00", GoVersion="go1.17.7", Compiler="gc", Platform="linux/amd64"
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Please type your answer here. eg: on-premise jira server v8.20.6
    ```
3. What operating system are you using? Also mention version.
```
   Linux 5.13.0-30-generic #33~20.04.1-Ubuntu SMP Mon Feb 7 14:25:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux    
```
4. What terminal are you using? Also mention version.
    ```
   windows terminal , ssh to linux. 
    ```

**To Reproduce**

1. jira issue create 
2. fillup with type,parent id,  summary, and then summit. 
3. gh.epic.error.not.found 

**Expected behavior**

**Screenshots**

**Additional context**

```
board:
  id: 11111
  name: 
  type: kanban
epic:
  name: 51411
  link: 51410
installation: Local
issue:
  types:
  - id: "7"
    name: Epic
    handle: ""
    subtask: false
  - id: "11"
    name: User Story
    handle: ""
    subtask: false
  - id: "6"
    name: Backlog Item
    handle: ""
    subtask: false
  - id: "10"
    name: Impediment
    handle: ""
    subtask: false
  - id: "5"
    name: Task
    handle: ""
    subtask: true
  - id: "1"
    name: Bug
    handle: ""
    subtask: false
  - id: "8"
    name: Business Case
    handle: ""
    subtask: false
  - id: "9"
    name: Roadmap Item
    handle: ""
    subtask: false
  - id: "12"
    name: Activity
    handle: ""
    subtask: false
login: username
project:
  key: abc
  type: ""
server: https://my.domain.com
```
