### ISSUE TITLE
`clone` command does not clone custom field values

### ISSUE THREAD

**Issue by coltoneakins** [ankitpokhrel/jira-cli#499]
**Describe the bug**

As it stands, the `jira clone` command does not really 'clone' issues in the same way Jira actually would. Issue custom fields are not copied over at all (the custom fields listed in `.config/.jira/.config.yml `).

Part of my .config.yml file:

```yaml
issue:
    fields:
        custom:
            - name: Story Points
              key: customfield_10103
              schema:
                datatype: number
            - name: Stakeholders
              key: customfield_13875
              schema:
                datatype: array
                items: option
            - name: Epic Link
              key: customfield_11405
              schema:
                datatype: any
            - name: Sprint
              key: customfield_10801
              schema:
                datatype: array
                items: string
            - name: Parent Link
              key: customfield_13803
              schema:
                datatype: any
            - name: Epic Name
              key: customfield_11407
              schema:
                datatype: string
```

None of these custom fields are copied over when cloning an issue.

For instance, when cloning issue:

ISSUE-12345

to 

ISSUE-12346

The cloned issue does not have custom fields set at all.

**Please provide following details**
1. JiraCLI Version:
    ```
    Please paste the output of `jira version` here.
    ```
2. Are you using Jira cloud or on-premise jira server? Also mention the version for on-premise installation.
    ```
    Jira on-premise, Jira v8.22.6
    ```
3. What operating system are you using? Also mention version.
    ```
    macOS Monterey v12.4
    ```
4. What terminal are you using? Also mention version.
    ```
    Hyper v3.3.0
    ```

**To Reproduce**

1. Setup jira-cli as you normally would
2. Attempt to clone any issue with custom labels 
3. See error

**Expected behavior**
Cloning an issue also clones the values of all custom fields.

**Screenshots**
n/a

**Additional context**
n/a
