### ISSUE TITLE
Can't update custom fields

### ISSUE THREAD

**Issue by snpefk** [ankitpokhrel/jira-cli#548]
**Describe the bug**
Can't update custom field "Fix build". 

**Please provide following details**
1. JiraCLI Version:
    ```
    # wierd output, AUR package says that it's "jira-cli-1.2.0-1"
    (Version="v0.0.0-dev", GitCommit="", CommitDate="", GoVersion="go1.19.4", Compiler="gc", Platform="linux/amd64") 
    ```
2. Are you using Jira cloud or on-premise jira server?
    ```
    SERVER INFO
    -----------
    
    Version: 	 8.22.0
    Build Number: 	 822000
    Deployment Type: Server
    Default Locale:  

    ```
3. What operating system are you using? Also mention version.
    ```
    Linux 5.15.86-1-MANJARO 
    ```
4. What terminal are you using? Also mention version.
    ```
    alacritty 0.11.0 (8dbaa0bb)
    ```

**To Reproduce**

1. `jira issue edit CORE-1000 --custom fix-build="1.0.0" --no-input --debug`
2. See error

**Expected behavior**
Successfully update issue  

**Screenshots**
```
Error:
  - Can not instantiate value of type [simple type, class com.atlassian.jira.rest.api.issue.FieldOperation] from JSON String; no single-String constructor/factory method (through reference chain: com.atlassian.jira.rest.v2.issue.IssueUpdateBean["update"])

jira: Received unexpected response '400 '.
Please check the parameters you supplied and try again.
```

**Additional context**
```yaml
# .config.yml
…
issue:
    fields:
        custom:
            - name: Fix Build
              key: customfield_18702
              schema:
                datatype: array
                items: string
…
```
