### ISSUE TITLE
Unable to use custom issue fields with arrays of users

### ISSUE THREAD

**Issue by aes256Slater** [ankitpokhrel/jira-cli#579]
**Describe the bug**

Custom fields with arrays of users seem to be problematic

I have a config with

```yml
            - name: Reviewers
              key: customfield_12300
              schema:
                datatype: array
                items: user
```

Yet any input given for `--custom reviewers=something` always fails

```bash
jira issue create \
    --config config.yml \
    --project "TEST" \
    --type "Test ticket" \
    --summary "Testing ticket creation" \
    --template "./description_template" \
    --assignee "${ASSIGNEE}" \
    --custom "reviewers"="Martin K" \
    --debug --no-input

Error:
  - customfield_10700: expected Object
```

**Please provide following details**
1. JiraCLI Version:
    ```
    $ jira version
(Version="v1.3.0", GitCommit="", CommitDate="", GoVersion="go1.19", Compiler="gc", Platform="linux/amd64")
    ```
2. Are you using Jira cloud or on-premise jira server?
    ```
    SERVER INFO
-----------

Version:         9.4.2
Build Number:    940002
Deployment Type: Server
Default Locale:
    ```
3. What operating system are you using? Also mention version.
    ```
    Linux Mint 20
    ```
4. What terminal are you using? Also mention version.
    ```
    GNOME Terminal v3.28.1
    ```
